Repository opentelekomcloud-infra/customer-service-monitoring, pull requests merged in 2019-10, with the labels that each got.

#50 Fix not working workspace changing for scenario1
  scenarios/scenario1/infrastructure.tf
  scenarios/scenario1/resources/loadbalancer.tf
  scenarios/scenario1/resources/variables.tf
  scenarios/scenario1/resources/vm.tf
  scenarios/scenario1/terraform.tfvars
  scenarios/scenario1/variables.tf
Labels: bug, scenario

#57 checksum integration
  roles/too_simple_server/tasks/main.yml
  roles/too_simple_server/vars/main.yml
Labels: enhancement

#51 Feature/scenario1 test2
  playbooks/scenario1_stop_server_on_random_node.yml
  roles/scenario1_portforwarding/tasks/main.yml
  scenarios/build.sh
  scenarios/scenario1/infrastructure.tf
  scenarios/scenario1/pre_build.sh
  scenarios/scenario1/resources/loadbalancer.tf
  scenarios/scenario1/resources/variables.tf
  scenarios/scenario1/terraform.tfvars
  scenarios/scenario1/test/continuous.py
  scenarios/scenario1/test/main.sh
  scenarios/scenario1/test/rebalance_test.py
  scenarios/scenario1/test/single.sh
  scenarios/scenario1/test2.tfvars
  scenarios/scenario1/variables.tf
Labels: enhancement, scenario

#58 S1T2 Stability fixes
  scenarios/scenario1/test/rebalance_test.py
  scenarios/scenario1/test/single.sh
Labels: bug

#59 Fixed some requirements versions
  requirements.txt
  scenarios/test.sh
Labels: bug

#62 Feature/nodes additional metrics
  playbooks/install_telegraf_client.yml
  roles/telegraf-client/defaults/main.yml
  roles/telegraf-client/handlers/main.yml
  roles/telegraf-client/tasks/main.yml
  roles/telegraf-client/templates/etc/yum.repos.d/influxdata.repo.j2
  roles/telegraf-client/templates/systemd/system/telegraf.service.d/override.conf
  roles/telegraf-client/templates/telegraf.conf.j2
  roles/telegraf-client/vars/main.yml
  scenarios/core/create_inventory.py
Labels: enhancement

#63 added interfaces to listen
  roles/telegraf-client/defaults/main.yml
Labels: enhancement

#64 Add timeout for sending metrics to telegraf
  scenarios/scenario1/test/continuous.py
Labels: bug

#66 telegraf client now installed with too simple server
  playbooks/scenario1_setup.yml
Labels: enhancement

#67 Use multiple AZ for load app nodes
  scenarios/scenario1/resources/vm.tf
Labels: enhancement

#68 Get rid of Session for telegraf reports
  scenarios/scenario1/test/continuous.py
Labels: bug

#71 Feature/include grafana boards
  playbooks/files/grafana/LB_DOWN.json
  playbooks/files/grafana/LB_LOAD.json
Labels: enhancement

#72 Add timeout for requests to LB
  scenarios/scenario1/test/continuous.py
Labels: bug

#74 Add request timeout panel to LB_LOAD dashboard
  playbooks/files/grafana/LB_LOAD.json
Labels: enhancement

#75 Feature/scenario3
  playbooks/files/grafana/HDD_TEST.json
  playbooks/scenario3_setup.yml
  scenarios/core/create_inventory.py
  scenarios/modules/bastion/vm.tf
  scenarios/scenario1/resources/first_boot.sh
  scenarios/scenario3/infrastructure.tf
  scenarios/scenario3/post_build.sh
  scenarios/scenario3/pre_build.sh
  scenarios/scenario3/resources/variables.tf
  scenarios/scenario3/resources/volumes.tf
  scenarios/scenario3/settings.tf
  scenarios/scenario3/terraform.tfvars
  scenarios/scenario3/variables.tf
Labels: enhancement

#76 Increased time interval for all LB_LOAD plots
  playbooks/files/grafana/LB_LOAD.json
Labels: enhancement

#78 Moved tests to csm-test-utils package
  requirements.txt
  scenarios/scenario1/test/continuous.py
  scenarios/scenario1/test/main.sh
  scenarios/scenario1/test/rebalance_test.py
  scenarios/scenario1/test/single.sh
Labels: enhancement

#81 Fixed net graphics for LB_LOAD dashboard
  playbooks/files/grafana/LB_LOAD.json
Labels: bug

#83 Minor update of LB_... boards
  playbooks/files/grafana/LB_DOWN.json
  playbooks/files/grafana/LB_LOAD.json
Labels: enhancement

#87 Add new LB_LOAD_high_res board
  playbooks/files/grafana/LB_LOAD_high_res.json
Labels: enhancement

#84 Feature/scenario2 telegraf postgres
  playbooks/scenario2_setup.yml
  requirements.txt
  roles/too_simple_server/defaults/main.yml
  roles/too_simple_server/templates/config.yml.j2
  roles/too_simple_server/vars/main.yml
  scenarios/core/create_inventory.py
  scenarios/scenario2/pre_build.sh
  scenarios/scenario2/terraform.tfvars
  scenarios/scenario2/test/main.py
  scenarios/scenario2/test/main.sh
Labels: enhancement, scenario

#91 Fix/test scripts
  requirements.txt
  scenarios/scenario2/test/main.sh
  scenarios/test.sh
Labels: bug

#92 Feature/dashboards variable
  playbooks/files/grafana/HDD_TEST.json
  playbooks/files/grafana/LB_LOAD.json
  playbooks/files/grafana/LB_LOAD_high_res.json
Labels: enhancement

#94 Fix/restart server after update
  roles/too_simple_server/tasks/main.yml
  roles/too_simple_server/vars/main.yml
Labels: bug

#85 Feature/scenario4
  .gitignore
  images/build_image.sh
  images/scenario4/packer_image.json
  images/scenario4/scripts/provision.sh
  images/secrets/.gitkeep
  install_packer.sh
  playbooks/files/grafana/AUTOSCALING.json
  playbooks/scenario4_setup.yml
  scenarios/scenario4/infrastructure.tf
  scenarios/scenario4/post_build.sh
  scenarios/scenario4/pre_build.sh
  scenarios/scenario4/resources/autoscaling.tf
  scenarios/scenario4/resources/first_boot.sh
  scenarios/scenario4/resources/loadbalancer.tf
  scenarios/scenario4/resources/variables.tf
  scenarios/scenario4/resources/vm.tf
  scenarios/scenario4/settings.tf
  scenarios/scenario4/terraform.tfvars
  scenarios/scenario4/test/main.sh
  scenarios/scenario4/variables.tf
Labels: enhancement, scenario
