Repository opentelekomcloud-infra/customer-service-monitoring, pull requests merged in 2019-11, with the labels that each got.

#104 Add galaxy requirement installation for `images` scenario
  images/test_host/packer_image.json
  scenarios/images/infrastructure.tf
  scenarios/scenario3/infrastructure.tf
  scenarios/scenario3/settings.tf
  scenarios/scenario3/terraform.tfvars
  scenarios/scenario4/infrastructure.tf
  scenarios/scenario4/settings.tf
Labels: bug

#105 Feature/scenarios migration
  images/scenario4/packer_image.json
  images/scenario4/scripts/provision.sh
  playbooks/files/nginx/nginx_config/ssl_nginx.conf
  playbooks/files/nginx/nginx_config/telegraf_nginx.conf
  playbooks/files/nginx/nginx_keys/.gitkeep
  playbooks/scenario1_setup.yml
  playbooks/scenario1_setup_telegraf_only.yml
  playbooks/scenario2_setup.yml
  playbooks/scenario4_image_setup.yml
  playbooks/scenario4_setup.yml
  scenarios/scenario4/infrastructure.tf
  scenarios/scenario4/resources/first_boot.sh
  scenarios/scenario4/resources/variables.tf
  scenarios/scenario4/terraform.tfvars
  scenarios/scenario4/variables.tf
Labels: enhancement

#109 Remove all mentioning of `csm-sandbox`
  CONTRIBUTING.md
  README.md
Labels: documentation

#114 Feature/nginx role
  playbooks/files/nginx/nginx_config/ssl_nginx.conf
  playbooks/files/nginx/nginx_config/telegraf_nginx.conf
  playbooks/scenario1_setup_telegraf_only.yml
  playbooks/scenario4_image_setup.yml
  playbooks/vars/nginx_extra_parameters.yml
  requirements.yml
  scenarios/scenario4/resources/first_boot.sh
Labels: enhancement

#119 Fix requirements path in ./test.sh
  playbooks/files/requirements.txt
  scenarios/test.sh
Labels: bug

#120 The vars file name is corrected
  playbooks/scenario1_setup.yml
  playbooks/scenario1_setup_telegraf_only.yml
  playbooks/scenario2_setup.yml
  playbooks/scenario3_setup.yml
  playbooks/scenario4_image_setup.yml
  playbooks/vars/telegraf_dbconnection_vars.yml
Labels: enhancement

#122 Feature/ssh key create if missing
  playbooks/files/requirements.txt
  scenarios/core/get_key.py
  scenarios/scenario3/pre_build.sh
  scenarios/scenario4/pre_build.sh
Labels: enhancement

#123 Update README.md
  README.md
Labels: bug, documentation

#125 Fix/security
  playbooks/files/requirements.txt
  scenarios/core/get_key.py
Labels: bug

#127 Feature/reg wait role
  playbooks/roles/register_host/defaults/main.yml
  playbooks/roles/register_host/files/wait_for_public_ip.py
  playbooks/roles/register_host/tasks/main.yml
  playbooks/scenario1_setup.yml
  playbooks/scenario1_stop_server_on_random_node.yml
  playbooks/scenario2_server_stop.yml
  playbooks/scenario2_setup.yml
  playbooks/scenario3_setup.yml
  playbooks/scenario4_setup.yml
Labels: enhancement

#128 Separate fixes from feature/test-infra
  ansible.cfg
  playbooks/test_host_setup.yml
  scenarios/core/create_inventory.py
Labels: bug, enhancement

#131 Fix/too simple
  playbooks/roles/too_simple_server/templates/config.yml.j2
Labels: bug

#134 Feature/prebuild to core
  scenarios/build.sh
  scenarios/core/pre_build.sh
  scenarios/scenario1/pre_build.sh
  scenarios/scenario3/pre_build.sh
  scenarios/scenario4/pre_build.sh
Labels: enhancement

#136 new default variable in bastion module
  scenarios/modules/bastion/variables.tf
  scenarios/modules/bastion/vm.tf
  scenarios/scenario1/infrastructure.tf
  scenarios/scenario3/infrastructure.tf
  scenarios/scenario4/infrastructure.tf
Labels: enhancement

#138 Minor changes after implementatios for csm-kapellmeister
  playbooks/test_host_setup.yml
  scenarios/core/create_inventory.py
  scenarios/core/get_key.py
  scenarios/core/pre_build.sh
  scenarios/scenario1/test/main.sh
  scenarios/test.sh
Labels: bug

#144 Fix/scenario4 AS rules
  scenarios/scenario4/resources/autoscaling.tf
Labels: bug

#142 Fix not building 2nd scenario
  ansible.cfg
  playbooks/roles/too_simple_server/templates/config.yml.j2
  playbooks/scenario2_setup.yml
  scenarios/modules/postgresql/instance.tf
  scenarios/modules/postgresql/variables.tf
  scenarios/scenario2/infrastructure.tf
  scenarios/scenario2/resources/net.tf
  scenarios/scenario2/resources/variables.tf
  scenarios/scenario2/resources/vm.tf
  scenarios/scenario2/settings.tf
  scenarios/scenario2/terraform.tfvars
  scenarios/scenario2/variables.tf
Labels: bug

#139 Feature/scenario3.5
  playbooks/scenario3_5_setup.yml
  scenarios/scenario3_5/infrastructure.tf
  scenarios/scenario3_5/post_build.sh
  scenarios/scenario3_5/resources/variables.tf
  scenarios/scenario3_5/resources/vm.tf
  scenarios/scenario3_5/resources/volume.tf
  scenarios/scenario3_5/settings.tf
  scenarios/scenario3_5/terraform.tfvars
  scenarios/scenario3_5/variables.tf
Labels: scenario

#145 Fixes for scenario1
  playbooks/roles/register_host/tasks/main.yml
  playbooks/scenario1_setup.yml
  playbooks/scenario1_setup_telegraf_only.yml
  playbooks/vars/nginx_extra_parameters.yml
  scenarios/images/infrastructure.tf
  scenarios/modules/public_router/network.tf
  scenarios/scenario1/infrastructure.tf
  scenarios/scenario1/post_build.sh
  scenarios/scenario1/resources/loadbalancer.tf
  scenarios/scenario1/resources/variables.tf
  scenarios/scenario1/resources/vm.tf
  scenarios/scenario1/terraform.tfvars
  scenarios/scenario1/test/main.sh
  scenarios/scenario1/test/single.sh
  scenarios/scenario1/variables.tf
  scenarios/scenario4/infrastructure.tf
Labels: bug, enhancement

#147 Feature/scenario3.5 provison
  playbooks/roles/iscsi_target/defaults/main.yml
  playbooks/roles/iscsi_target/tasks/main.yml
  playbooks/roles/iscsi_target/templates/config.yml.j2
  playbooks/roles/iscsi_target/vars/main.yml
  playbooks/scenario3_5_setup.yml
  playbooks/setup_telegraf_local.yml
  playbooks/vars/scenario_3_5_vars.yml
  scenarios/scenario3_5/infrastructure.tf
  scenarios/scenario3_5/post_build.sh
  scenarios/scenario3_5/resources/variables.tf
  scenarios/scenario3_5/resources/vm.tf
  scenarios/scenario3_5/resources/volume.tf
  scenarios/scenario3_5/terraform.tfvars
  scenarios/scenario3_5/variables.tf
Labels: enhancement, scenario

#149 Feature/scenario3 5 connection test
  playbooks/files/tgt_inst_conn_chk.sh
  playbooks/scenario3_5_setup.yml
Labels: enhancement

#148 Feature/scenario1 5
  .gitignore
  playbooks/scenario1_5_setup.yml
  playbooks/scenario1_5_stop_server_on_random_node.yml
  playbooks/scenario1_setup_grafana.yml
  scenarios/core/get_key.py
  scenarios/modules/bastion/variables.tf
  scenarios/modules/bastion/vm.tf
  scenarios/scenario1/infrastructure.tf
  scenarios/scenario1/resources/variables.tf
  scenarios/scenario1/resources/vm.tf
  scenarios/scenario1/test2.tfvars
  scenarios/scenario1_5/infrastructure.tf
  scenarios/scenario1_5/post_build.sh
  scenarios/scenario1_5/settings.tf
  scenarios/scenario1_5/terraform.tfvars
  scenarios/scenario1_5/test/main.sh
  scenarios/scenario1_5/variables.tf
Labels: enhancement

#153 Changed `INFLUX_PSWD` to standard `INFLUX_PASSWORD`
  playbooks/vars/telegraf_dbconnection_vars.yml
  scenarios/build.sh
Labels: bug

#155 Add env variables logging if no INFLUX_PASSWORD found
  scenarios/build.sh
Labels: enhancement
