Repository opentelekomcloud-infra/customer-service-monitoring, pull requests merged in 2020-12, with the labels that each got.

#254 Refactoring iscsi scenario infra
  playbooks/iscsi_monitoring_destroy.yml
  playbooks/iscsi_monitoring_setup.yml
  playbooks/setup_scenarios_controller.yml
  scenarios/iscsi_monitoring/infrastructure.tf
  scenarios/iscsi_monitoring/resources/settings.tf
  scenarios/iscsi_monitoring/resources/variables.tf
  scenarios/iscsi_monitoring/resources/vm.tf
  scenarios/iscsi_monitoring/resources/volume.tf
  scenarios/iscsi_monitoring/settings.tf
  scenarios/iscsi_monitoring/terraform.tfvars
  scenarios/iscsi_monitoring/variables.tf
  scenarios/modules/bastion/settings.tf
  scenarios/modules/public_router/settings.tf
Labels: refactoring

#262 Ref/iscsi provisioning
  playbooks/iscsi_monitoring_setup.yml
  playbooks/setup_scenarios_controller.yml
  playbooks/vars/scenario_iscsi_vars.yml
Labels: refactoring

#269 Add zuul CI integration
  .ansible-lint
  .pylintrc
  .travis.yml
  .yamllint
  .zuul.yaml
  README.md
  ansible-lint.sh
  lint-requirements.txt
  playbooks/files/requirements.txt
  tox.ini
Labels: gate

#270 Make yamllint use more tolerant configuration
  .yamllint
Labels: gate

#271 Add terraform linters to pipelines
  .zuul.yaml
  scripts/ansible-lint.sh
  scripts/prepare-terraform.sh
  scripts/terraform-lint.sh
  tox.ini
Labels: gate

#275 Run terraform fmt
  .zuul.yaml
  scenarios/dns_monitoring/variables.tf
  scenarios/iscsi_monitoring/infrastructure.tf
  scenarios/modules/bastion/network.tf
  scenarios/modules/ecs_node/variables.tf
  scenarios/modules/ecs_node/vm.tf
  scenarios/modules/loadbalancer/loadbalancer.tf
  scenarios/modules/postgresql/instance.tf
  scenarios/scenario1/infrastructure.tf
  scenarios/scenario1/settings.tf
  scenarios/scenario1/variables.tf
  scenarios/scenario1_5/infrastructure.tf
  scenarios/scenario1_5/settings.tf
  scenarios/scenario1_5/terraform.tfvars
  scenarios/scenario2/settings.tf
  scenarios/scenario4/infrastructure.tf
  scenarios/scenario4/resources/smn.tf
  scenarios/scenario4/settings.tf
  scenarios/scenario4/terraform.tfvars
  scenarios/scenario4/variables.tf
  scenarios/scenario6/infrastructure.tf
  scenarios/scenario6/resources/variables.tf
  scenarios/scenario6/settings.tf
  scenarios/scenario6/variables.tf
  scripts/terraform-lint.sh
Labels: gate

#276 Fix terraform-lint.sh
  .zuul.yaml
  scripts/terraform-lint.sh
Labels: gate

#278 Fix terraform validation in terraform-lint.sh
  scripts/terraform-lint.sh
Labels: gate

#285 Improve ecs node module
  scenarios/modules/ecs_node/settings.tf
  scenarios/modules/ecs_node/variables.tf
  scenarios/modules/ecs_node/vm.tf
Labels: gate

#282 refactoring lb monitoring
  playbooks/lb_monitoring_destroy.yml
  playbooks/lb_monitoring_setup.yml
  playbooks/scenario1_destroy.yml
  scenarios/lb_monitoring/infrastructure.tf
  scenarios/lb_monitoring/resources/settings.tf
  scenarios/lb_monitoring/resources/variables.tf
  scenarios/lb_monitoring/resources/vm.tf
  scenarios/lb_monitoring/settings.tf
  scenarios/lb_monitoring/terraform.tfvars
  scenarios/lb_monitoring/variables.tf
  scenarios/scenario1/infrastructure.tf
Labels: gate, refactoring

#283 Refactoring rds scenario
  playbooks/rds_monitoring_destroy.yml
  playbooks/rds_monitoring_server_stop.yml
  playbooks/rds_monitoring_setup.yml
  playbooks/scenario2_destroy.yml
  playbooks/scenario2_server_stop.yml
  scenarios/modules/postgresql/instance.tf
  scenarios/modules/postgresql/settings.tf
  scenarios/modules/postgresql/variables.tf
  scenarios/rds_monitoring/infrastructure.tf
  scenarios/rds_monitoring/resources/first_boot.sh
  scenarios/rds_monitoring/resources/settings.tf
  scenarios/rds_monitoring/resources/variables.tf
  scenarios/rds_monitoring/resources/vm.tf
  scenarios/rds_monitoring/settings.tf
  scenarios/rds_monitoring/terraform.tfvars
  scenarios/rds_monitoring/variables.tf
  scenarios/scenario2/infrastructure.tf
  scenarios/scenario2/resources/net.tf
  scenarios/scenario2/resources/variables.tf
  scenarios/scenario2/resources/vm.tf
  scenarios/scenario2/settings.tf
  scenarios/scenario2/terraform.tfvars
  scenarios/scenario2/variables.tf
Labels: gate

#284 Refactoring lb fail monitoring
  playbooks/lb_down_monitoring_destroy.yml
  playbooks/lb_down_monitoring_setup.yml
  playbooks/lb_down_monitoring_start_server.yml
  playbooks/lb_down_monitoring_stop_server_on_random_node.yml
  playbooks/scenario1_5_destroy.yml
  playbooks/scenario1_5_setup.yml
  playbooks/templates/lb_down_monitoring.yml
  scenarios/lb_down_monitoring/infrastructure.tf
  scenarios/lb_down_monitoring/resources/first_boot.sh
  scenarios/lb_down_monitoring/resources/settings.tf
  scenarios/lb_down_monitoring/resources/variables.tf
  scenarios/lb_down_monitoring/resources/vm.tf
  scenarios/lb_down_monitoring/settings.tf
  scenarios/lb_down_monitoring/terraform.tfvars
  scenarios/lb_down_monitoring/variables.tf
  scenarios/modules/ecs_node/vm.tf
  scenarios/scenario1_5/infrastructure.tf
  scenarios/scenario1_5/terraform.tfvars
  scenarios/scenario1_5/variables.tf
Labels: gate

#289 Ignore some flake8 import checks
  tox.ini
Labels: gate

#292 Fix flake8 errors in `create_inventory.py`
  scenarios/core/create_inventory.py
Labels: gate

#290 Refactor `cpu_load.py` to match `flake8` checks
  playbooks/files/autoscaling/cpu_load.py
Labels: gate

#293 Remove unused `get_key.py` in playbooks
  playbooks/files/get_key.py
Labels: gate

#294 Add unittest + coverage env to `tox.ini`
  test-requirements.txt
  tests/__init__.py
  tox.ini
Labels: gate

#296 Move setting `terraform_workspace` to inventory
  inventory/prod/group_vars/all.yml
Labels: gate

#298 Add control instance to as_monitoring scenario
  playbooks/as_monitoring_setup.yml
  scenarios/as_monitoring/infrastructure.tf
  scenarios/as_monitoring/resources/variables.tf
  scenarios/as_monitoring/resources/vm.tf
  scenarios/as_monitoring/terraform.tfvars
  scenarios/as_monitoring/variables.tf
Labels: gate

#297 Add unit testing job with docker
  .gitignore
  .zuul.yaml
  tests/postgres/pre.yaml
  tox.ini
Labels: gate

#291 Fix flake8 errors in `rds` library
  playbooks/files/rds/__init__.py
  playbooks/files/rds/__main__.py
  playbooks/files/rds/arg_parser.py
  playbooks/files/rds/base.py
  playbooks/files/rds/cli.py
  playbooks/files/rds/pg2/data.yaml
  playbooks/files/rds/pg2/db_methods.py
  playbooks/files/rds/sqla/data.yaml
  playbooks/files/rds/sqla/db_methods.py
  playbooks/files/rds/sqla/db_model.py
  playbooks/files/rds/sqla/session.py
  test-requirements.txt
  tests/otc-tox-docker/pre.yaml
  tests/rds_test_config.yaml
  tests/test_rds.py
Labels: gate

#299 Make python lint and unit tests voting
  .zuul.yaml
Labels: gate

#287 Prepare as monitoring for awx
  playbooks/as_monitoring_destroy.yml
  playbooks/as_monitoring_setup.yml
  playbooks/files/autoscaling/install_lookbusy.sh
  playbooks/setup_scenarios_controller.yml
  playbooks/vars/nginx_controller.yml
  scenarios/as_monitoring/terraform.tfvars
  scenarios/csm_controller/terraform.tfvars
  scenarios/rds_monitoring/resources/variables.tf
  scenarios/rds_monitoring/resources/vm.tf
  scenarios/scenario2/settings.tf
Labels: gate

#300 Ref/aws iscsi sfs
  playbooks/as_monitoring_destroy.yml
  playbooks/as_monitoring_setup.yml
  playbooks/iscsi_monitoring_destroy.yml
  playbooks/iscsi_monitoring_setup.yml
  playbooks/sfs_monitoring_destroy.yml
  playbooks/sfs_monitoring_setup.yml
Labels: gate

#301 Update readme
  README.md
Labels: gate

#303 Make `terraform-lint` job to use tox
  .zuul.yaml
  scripts/prepare-terraform.sh
  scripts/terraform-lint.sh
  tox.ini
Labels: gate

#305 Fix incorrect reference of `tox-cover-docker` `pre-run`
  .zuul.yaml
  tests/docker/pre.yaml
  tests/otc-tox-docker/pre.yaml
Labels: gate

#306 Ref/hdd dns awx
  playbooks/as_monitoring_setup.yml
  playbooks/dns_monitoring_destroy.yml
  playbooks/dns_monitoring_setup.yml
  playbooks/hdd_monitoring_destroy.yml
  playbooks/hdd_monitoring_setup.yml
  playbooks/iscsi_monitoring_setup.yml
  playbooks/rds_monitoring_setup.yml
  playbooks/scenario6_setup.yml
  playbooks/setup_scenarios_controller.yml
  playbooks/sfs_monitoring_setup.yml
  scenarios/csm_controller/infrastructure.tf
  scenarios/dns_monitoring/infrastructure.tf
  scenarios/dns_monitoring/resources/dns.tf
  scenarios/dns_monitoring/resources/settings.tf
  scenarios/dns_monitoring/resources/variables.tf
  scenarios/modules/loadbalancer/loadbalancer.tf
  scenarios/sfs_monitoring/infrastructure.tf
Labels: gate

#302 Fix linter issues
  .zuul.yaml
  playbooks/as_monitoring_setup.yml
  playbooks/dns_monitoring_setup.yml
  playbooks/hdd_monitoring_destroy.yml
  playbooks/lb_down_monitoring_destroy.yml
  playbooks/lb_down_monitoring_setup.yml
  playbooks/lb_monitoring_destroy.yml
  playbooks/lb_monitoring_setup.yml
  playbooks/prepare_config.yml
  playbooks/rds_monitoring_destroy.yml
  playbooks/rds_monitoring_setup.yml
  playbooks/scenario6_destroy.yml
  playbooks/scenario6_setup.yml
  playbooks/sfs_monitoring_setup.yml
  playbooks/vars/scenario_iscsi_vars.yml
  scenarios/scenario6/infrastructure.tf
  scenarios/scenario6/resources/net.tf
  scenarios/scenario6/resources/variables.tf
  scenarios/scenario6/resources/vm.tf
  scenarios/scenario6/settings.tf
  scenarios/scenario6/terraform.tfvars
  scenarios/scenario6/variables.tf
Labels: gate

#311 Ref/rds awx
  playbooks/dns_monitoring_setup.yml
  playbooks/rds_monitoring_destroy.yml
  playbooks/rds_monitoring_server_stop.yml
  playbooks/rds_monitoring_setup.yml
Labels: gate

#313 default workspace
  inventory/prod/group_vars/all.yml
Labels: gate

#315 Ref/lb awx
  playbooks/lb_monitoring_setup.yml
  playbooks/vars/nginx_controller.yml
Labels: gate

#316 Remove unused `get_key.py` from `scenarios/core`
  scenarios/core/get_key.py
Labels: gate

#319 Fix lb_down_test.sh
  playbooks/files/lb_down_test.sh
Labels: gate

#320 Fix incorrect terraform validate call
  scripts/terraform-lint.sh
Labels: gate

#295 Rds backup monitoring
  playbooks/files/rds/rds-backup-requirements.txt
  playbooks/rds_backup_monitoring_destroy.yml
  playbooks/rds_backup_monitoring_setup.yml
  scenarios/rds_backup_monitoring/infrastructure.tf
  scenarios/rds_backup_monitoring/resources/first_boot.sh
  scenarios/rds_backup_monitoring/resources/settings.tf
  scenarios/rds_backup_monitoring/resources/variables.tf
  scenarios/rds_backup_monitoring/resources/vm.tf
  scenarios/rds_backup_monitoring/settings.tf
  scenarios/rds_backup_monitoring/terraform.tfvars
  scenarios/rds_backup_monitoring/variables.tf
Labels: gate

#322 Fix rds backup monitoring
  playbooks/rds_backup_monitoring_setup.yml
Labels: gate

#323 Backward compatibility fix for telegraf client role
  roles/telegraf-client
Labels: gate
