Repository opentelekomcloud-infra/customer-service-monitoring, pull requests merged in 2020-01, with the labels that each got.

#177 Init terraform before destroy
  playbooks/scenario2_setup.yml
  scenarios/destroy.sh
Labels: bug

#178 Added prefix for scenario 1 and 1_5
  scenarios/scenario1/resources/loadbalancer.tf
  scenarios/scenario1/resources/vm.tf
Labels: bug

#182 removed obsolete test
  scenarios/scenario4/test/main.sh
Labels: bug

#183 Made scenario1_5 independent from scenario1
  scenarios/modules/bastion/vm.tf
  scenarios/modules/ecs_node/first_boot.sh
  scenarios/modules/ecs_node/variables.tf
  scenarios/modules/ecs_node/vm.tf
  scenarios/modules/loadbalancer/loadbalancer.tf
  scenarios/modules/loadbalancer/variables.tf
  scenarios/scenario1_5/infrastructure.tf
  scenarios/scenario1_5/variables.tf
Labels: enhancement

#186 using modules in all possible scenarios
  playbooks/scenario2_setup.yml
  scenarios/modules/loadbalancer/loadbalancer.tf
  scenarios/scenario1/infrastructure.tf
  scenarios/scenario1/resources/first_boot.sh
  scenarios/scenario1/resources/loadbalancer.tf
  scenarios/scenario1/resources/variables.tf
  scenarios/scenario1/resources/vm.tf
  scenarios/scenario2/infrastructure.tf
  scenarios/scenario2/terraform.tfvars
  scenarios/scenario2/test/main.sh
  scenarios/scenario2/variables.tf
  scenarios/scenario4/infrastructure.tf
  scenarios/scenario4/resources/autoscaling.tf
  scenarios/scenario4/resources/loadbalancer.tf
  scenarios/scenario4/resources/smn.tf
  scenarios/scenario4/resources/variables.tf
  scenarios/scenario4/resources/vm.tf
Labels: bug, enhancement

#190 Using bastion module in scenario_3_5
  playbooks/scenario3_5_setup.yml
  playbooks/vars/scenario_3_5_vars.yml
  scenarios/modules/bastion/network.tf
  scenarios/scenario3_5/infrastructure.tf
  scenarios/scenario3_5/post_build.sh
  scenarios/scenario3_5/resources/variables.tf
  scenarios/scenario3_5/resources/vm.tf
  scenarios/scenario3_5/resources/volume.tf
  scenarios/scenario3_5/terraform.tfvars
Labels: enhancement

#193 fixed project path
  playbooks/scenario1_5_setup.yml
Labels: bug

#194 fixed variable name
  scenarios/scenario2/test/main.sh
Labels: bug
